workflows:
  android-wizard:
    name: Compilar Loja F-lite
    max_build_duration: 10
    instance_type: mac_mini_m1
    scripts:
      - name: Descompactar projeto
        script: unzip fdroidclient.zip && mv fdroidclient/* . || true
      - name: Dar permissao de execucao
        script: chmod +x gradlew
      - name: Gerar APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
